include:
  - tools.java.installed
  - tools.maven.installed
  - tools.gradle
  - tools.groovy
  - tools.scala
  - tools.docker.installed
  - tools.python.installed
  - tools.node.installed
  - jenkins.installed
  - users.present
  - jenkins.nginx.installed-secure-ssl